-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

SET search_path = public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS issue_changes_idt ON issue_changes CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_issue_changes_idt() RETURNS trigger AS $BODY$
BEGIN IF NEW.id IS null THEN SELECT nextval('issue_changes_seq') INTO STRICT NEW.id; END IF; RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_issue_changes_idt() FROM PUBLIC;

CREATE TRIGGER issue_changes_idt
	BEFORE INSERT ON issue_changes FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_issue_changes_idt();

