-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

SET search_path = public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS perm_tpl_characteristics_idt ON perm_tpl_characteristics CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_perm_tpl_characteristics_idt() RETURNS trigger AS $BODY$
BEGIN IF NEW.id IS null THEN SELECT nextval('perm_tpl_characteristics_seq') INTO STRICT NEW.id; END IF; RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_perm_tpl_characteristics_idt() FROM PUBLIC;

CREATE TRIGGER perm_tpl_characteristics_idt
	BEFORE INSERT ON perm_tpl_characteristics FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_perm_tpl_characteristics_idt();

