-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

SET search_path = public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS project_qprofiles_idt ON project_qprofiles CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_project_qprofiles_idt() RETURNS trigger AS $BODY$
BEGIN IF NEW.id IS null THEN SELECT nextval('project_qprofiles_seq') INTO STRICT NEW.id; END IF; RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_project_qprofiles_idt() FROM PUBLIC;

CREATE TRIGGER project_qprofiles_idt
	BEFORE INSERT ON project_qprofiles FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_project_qprofiles_idt();

