-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

SET search_path = public;
\set ON_ERROR_STOP ON

\i ./schema/triggers/ACTIVE_RULES_IDT_trigger.sql
\i ./schema/triggers/ACTIVE_RULE_PARAMETERS_IDT_trigger.sql
\i ./schema/triggers/CE_ACTIVITY_IDT_trigger.sql
\i ./schema/triggers/CE_QUEUE_IDT_trigger.sql
\i ./schema/triggers/DUPLICATIONS_INDEX_IDT_trigger.sql
\i ./schema/triggers/EVENTS_IDT_trigger.sql
\i ./schema/triggers/FILE_SOURCES_IDT_trigger.sql
\i ./schema/triggers/GROUPS_IDT_trigger.sql
\i ./schema/triggers/GROUP_ROLES_IDT_trigger.sql
\i ./schema/triggers/ISSUES_IDT_trigger.sql
\i ./schema/triggers/ISSUE_CHANGES_IDT_trigger.sql
\i ./schema/triggers/LOADED_TEMPLATES_IDT_trigger.sql
\i ./schema/triggers/MANUAL_MEASURES_IDT_trigger.sql
\i ./schema/triggers/METRICS_IDT_trigger.sql
\i ./schema/triggers/NOTIFICATIONS_IDT_trigger.sql
\i ./schema/triggers/PERMISSION_TEMPLATES_IDT_trigger.sql
\i ./schema/triggers/PERM_TEMPLATES_GROUPS_IDT_trigger.sql
\i ./schema/triggers/PERM_TEMPLATES_USERS_IDT_trigger.sql
\i ./schema/triggers/PERM_TPL_CHARACTERISTICS_IDT_trigger.sql
\i ./schema/triggers/PROJECTS_IDT_trigger.sql
\i ./schema/triggers/PROJECT_LINKS_IDT_trigger.sql
\i ./schema/triggers/PROJECT_MEASURES_IDT_trigger.sql
\i ./schema/triggers/PROJECT_QPROFILES_IDT_trigger.sql
\i ./schema/triggers/PROPERTIES_IDT_trigger.sql
\i ./schema/triggers/QUALITY_GATES_IDT_trigger.sql
\i ./schema/triggers/QUALITY_GATE_CONDITIONS_IDT_trigger.sql
\i ./schema/triggers/RULES_IDT_trigger.sql
\i ./schema/triggers/RULES_PARAMETERS_IDT_trigger.sql
\i ./schema/triggers/RULES_PROFILES_IDT_trigger.sql
\i ./schema/triggers/SNAPSHOTS_IDT_trigger.sql
\i ./schema/triggers/USERS_IDT_trigger.sql
\i ./schema/triggers/USER_ROLES_IDT_trigger.sql
\i ./schema/triggers/USER_TOKENS_IDT_trigger.sql
