-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

SET search_path = public;
\set ON_ERROR_STOP ON

DROP TRIGGER IF EXISTS users_idt ON users CASCADE;
CREATE OR REPLACE FUNCTION trigger_fct_users_idt() RETURNS trigger AS $BODY$
BEGIN IF NEW.id IS null THEN SELECT nextval('users_seq') INTO STRICT NEW.id; END IF; RETURN NEW;
END
$BODY$
 LANGUAGE 'plpgsql' SECURITY DEFINER;
-- REVOKE ALL ON FUNCTION trigger_fct_users_idt() FROM PUBLIC;

CREATE TRIGGER users_idt
	BEFORE INSERT ON users FOR EACH ROW
	EXECUTE PROCEDURE trigger_fct_users_idt();

