-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET search_path = public;
ALTER TABLE active_rules ADD PRIMARY KEY (id);
ALTER TABLE active_rule_parameters ADD PRIMARY KEY (id);
ALTER TABLE analysis_properties ADD PRIMARY KEY (uuid);
ALTER TABLE ce_activity ADD PRIMARY KEY (id);
ALTER TABLE ce_queue ADD PRIMARY KEY (id);
ALTER TABLE ce_scanner_context ADD PRIMARY KEY (task_uuid);
ALTER TABLE ce_task_characteristics ADD PRIMARY KEY (uuid);
ALTER TABLE ce_task_input ADD PRIMARY KEY (task_uuid);
ALTER TABLE default_qprofiles ADD PRIMARY KEY (organization_uuid,language);
ALTER TABLE duplications_index ADD PRIMARY KEY (id);
ALTER TABLE es_queue ADD PRIMARY KEY (uuid);
ALTER TABLE events ADD PRIMARY KEY (id);
ALTER TABLE file_sources ADD PRIMARY KEY (id);
ALTER TABLE groups ADD PRIMARY KEY (id);
ALTER TABLE group_roles ADD PRIMARY KEY (id);
ALTER TABLE internal_properties ADD PRIMARY KEY (kee);
ALTER TABLE issues ADD PRIMARY KEY (id);
ALTER TABLE issue_changes ADD PRIMARY KEY (id);
ALTER TABLE loaded_templates ADD PRIMARY KEY (id);
ALTER TABLE manual_measures ADD PRIMARY KEY (id);
ALTER TABLE metrics ADD PRIMARY KEY (id);
ALTER TABLE notifications ADD PRIMARY KEY (id);
ALTER TABLE organizations ADD PRIMARY KEY (uuid);
ALTER TABLE organization_members ADD PRIMARY KEY (organization_uuid,user_id);
ALTER TABLE org_qprofiles ADD PRIMARY KEY (uuid);
ALTER TABLE permission_templates ADD PRIMARY KEY (id);
ALTER TABLE perm_templates_groups ADD PRIMARY KEY (id);
ALTER TABLE perm_templates_users ADD PRIMARY KEY (id);
ALTER TABLE perm_tpl_characteristics ADD PRIMARY KEY (id);
ALTER TABLE plugins ADD PRIMARY KEY (uuid);
ALTER TABLE projects ADD PRIMARY KEY (id);
ALTER TABLE project_branches ADD PRIMARY KEY (uuid);
ALTER TABLE project_links ADD PRIMARY KEY (id);
ALTER TABLE project_measures ADD PRIMARY KEY (id);
ALTER TABLE project_qprofiles ADD PRIMARY KEY (id);
ALTER TABLE properties ADD PRIMARY KEY (id);
ALTER TABLE qprofile_changes ADD PRIMARY KEY (kee);
ALTER TABLE qprofile_edit_groups ADD PRIMARY KEY (uuid);
ALTER TABLE qprofile_edit_users ADD PRIMARY KEY (uuid);
ALTER TABLE quality_gates ADD PRIMARY KEY (id);
ALTER TABLE quality_gate_conditions ADD PRIMARY KEY (id);
ALTER TABLE rules ADD PRIMARY KEY (id);
ALTER TABLE rules_metadata ADD PRIMARY KEY (rule_id,organization_uuid);
ALTER TABLE rules_parameters ADD PRIMARY KEY (id);
ALTER TABLE rules_profiles ADD PRIMARY KEY (id);
ALTER TABLE rule_repositories ADD PRIMARY KEY (kee);
ALTER TABLE snapshots ADD PRIMARY KEY (id);
ALTER TABLE users ADD PRIMARY KEY (id);
ALTER TABLE user_roles ADD PRIMARY KEY (id);
ALTER TABLE user_tokens ADD PRIMARY KEY (id);
ALTER TABLE webhook_deliveries ADD PRIMARY KEY (uuid);
