-- Generated by Ora2Pg, the Oracle database Schema converter, version 20.0
-- Copyright 2000-2019 Gilles DAROLD. All rights reserved.
-- DATASOURCE: dbi:Oracle:db1

SET client_encoding TO 'UTF8';

\set ON_ERROR_STOP ON

SET search_path = public;

CREATE TABLE active_rules (
	id numeric(38) NOT NULL,
	profile_id numeric(38) NOT NULL,
	rule_id numeric(38) NOT NULL,
	failure_level numeric(38) NOT NULL,
	inheritance varchar(10),
	created_at numeric(38),
	updated_at numeric(38)
) ;

CREATE TABLE active_rule_parameters (
	id numeric(38) NOT NULL,
	active_rule_id numeric(38) NOT NULL,
	rules_parameter_id numeric(38) NOT NULL,
	value varchar(4000),
	rules_parameter_key varchar(128)
) ;

CREATE TABLE analysis_properties (
	uuid varchar(40) NOT NULL,
	snapshot_uuid varchar(40) NOT NULL,
	kee varchar(512) NOT NULL,
	text_value varchar(4000),
	clob_value text,
	is_empty smallint NOT NULL,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE ce_activity (
	id numeric(38) NOT NULL,
	uuid varchar(40) NOT NULL,
	task_type varchar(15) NOT NULL,
	component_uuid varchar(40),
	status varchar(15) NOT NULL,
	is_last smallint NOT NULL,
	is_last_key varchar(55) NOT NULL,
	submitter_login varchar(255),
	submitted_at numeric(38) NOT NULL,
	started_at numeric(38),
	executed_at numeric(38),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL,
	execution_time_ms numeric(38),
	analysis_uuid varchar(50),
	error_message varchar(1000),
	error_stacktrace text,
	worker_uuid varchar(40),
	execution_count numeric(38) NOT NULL,
	error_type varchar(20)
) ;

CREATE TABLE ce_queue (
	id numeric(38) NOT NULL,
	uuid varchar(40) NOT NULL,
	task_type varchar(15) NOT NULL,
	component_uuid varchar(40),
	status varchar(15),
	submitter_login varchar(255),
	started_at numeric(38),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL,
	worker_uuid varchar(40),
	execution_count numeric(38) NOT NULL
) ;

CREATE TABLE ce_scanner_context (
	task_uuid varchar(40) NOT NULL,
	context_data bytea NOT NULL,
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE ce_task_characteristics (
	uuid varchar(40) NOT NULL,
	task_uuid varchar(40) NOT NULL,
	kee varchar(512) NOT NULL,
	text_value varchar(512)
) ;

CREATE TABLE ce_task_input (
	task_uuid varchar(40) NOT NULL,
	input_data bytea,
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE default_qprofiles (
	organization_uuid varchar(40) NOT NULL,
	language varchar(20) NOT NULL,
	qprofile_uuid varchar(255) NOT NULL,
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE duplications_index (
	id numeric(38) NOT NULL,
	hash varchar(50) NOT NULL,
	index_in_file numeric(38) NOT NULL,
	start_line numeric(38) NOT NULL,
	end_line numeric(38) NOT NULL,
	component_uuid varchar(50) NOT NULL,
	analysis_uuid varchar(50) NOT NULL
) ;

CREATE TABLE es_queue (
	uuid varchar(40) NOT NULL,
	doc_type varchar(40) NOT NULL,
	doc_id varchar(4000) NOT NULL,
	doc_id_type varchar(20),
	doc_routing varchar(4000),
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE events (
	id numeric(38) NOT NULL,
	name varchar(400),
	category varchar(50),
	description varchar(4000),
	event_data varchar(4000),
	event_date numeric(38) NOT NULL,
	created_at numeric(38) NOT NULL,
	component_uuid varchar(50) NOT NULL,
	analysis_uuid varchar(50) NOT NULL,
	uuid varchar(40) NOT NULL
) ;

CREATE TABLE file_sources (
	id numeric(38) NOT NULL,
	project_uuid varchar(50) NOT NULL,
	file_uuid varchar(50) NOT NULL,
	line_hashes text,
	data_hash varchar(50),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL,
	src_hash varchar(50),
	binary_data bytea,
	data_type varchar(20),
	revision varchar(100)
) ;

CREATE TABLE groups (
	id numeric(38) NOT NULL,
	name varchar(500),
	description varchar(200),
	created_at timestamp,
	updated_at timestamp,
	organization_uuid varchar(40) NOT NULL
) ;

CREATE TABLE groups_users (
	user_id numeric(38),
	group_id numeric(38)
) ;

CREATE TABLE group_roles (
	id numeric(38) NOT NULL,
	group_id numeric(38),
	resource_id numeric(38),
	role varchar(64) NOT NULL,
	organization_uuid varchar(40) NOT NULL
) ;

CREATE TABLE internal_properties (
	kee varchar(20) NOT NULL,
	is_empty smallint NOT NULL,
	text_value varchar(4000),
	clob_value text,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE issues (
	id numeric(38) NOT NULL,
	kee varchar(50) NOT NULL,
	rule_id numeric(38),
	severity varchar(10),
	manual_severity smallint NOT NULL,
	message varchar(4000),
	line numeric(38),
	gap decimal(30,20),
	status varchar(20),
	resolution varchar(20),
	checksum varchar(1000),
	reporter varchar(255),
	assignee varchar(255),
	author_login varchar(255),
	action_plan_key varchar(50),
	issue_attributes varchar(4000),
	effort numeric(38),
	created_at numeric(38),
	updated_at numeric(38),
	issue_creation_date numeric(38),
	issue_update_date numeric(38),
	issue_close_date numeric(38),
	tags varchar(4000),
	component_uuid varchar(50),
	project_uuid varchar(50),
	locations bytea,
	issue_type smallint
) ;

CREATE TABLE issue_changes (
	id numeric(38) NOT NULL,
	kee varchar(50),
	issue_key varchar(50) NOT NULL,
	user_login varchar(255),
	change_type varchar(20),
	change_data text,
	created_at numeric(38),
	updated_at numeric(38),
	issue_change_creation_date numeric(38)
) ;

CREATE TABLE loaded_templates (
	id numeric(38) NOT NULL,
	kee varchar(200),
	template_type varchar(64) NOT NULL
) ;

CREATE TABLE manual_measures (
	id numeric(38) NOT NULL,
	metric_id numeric(38) NOT NULL,
	value decimal(38,20),
	text_value varchar(4000),
	user_login varchar(255),
	description varchar(4000),
	created_at numeric(38),
	updated_at numeric(38),
	component_uuid varchar(50) NOT NULL
) ;

CREATE TABLE metrics (
	id numeric(38) NOT NULL,
	name varchar(64) NOT NULL,
	description varchar(255),
	direction numeric(38) NOT NULL DEFAULT 0,
	domain varchar(64),
	short_name varchar(64),
	qualitative smallint NOT NULL DEFAULT 0,
	val_type varchar(8),
	user_managed smallint DEFAULT 0,
	enabled smallint DEFAULT 1,
	worst_value decimal(38,20),
	best_value decimal(38,20),
	optimized_best_value smallint,
	hidden smallint,
	delete_historical_data smallint,
	decimal_scale numeric(38)
) ;

CREATE TABLE notifications (
	id numeric(38) NOT NULL,
	data bytea
) ;

CREATE TABLE organizations (
	uuid varchar(40) NOT NULL,
	kee varchar(32) NOT NULL,
	name varchar(64) NOT NULL,
	description varchar(256),
	url varchar(256),
	avatar_url varchar(256),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL,
	default_perm_template_project varchar(40),
	default_perm_template_view varchar(40),
	guarded smallint NOT NULL,
	user_id numeric(38),
	default_group_id numeric(38),
	new_project_private smallint NOT NULL
) ;

CREATE TABLE organization_members (
	organization_uuid varchar(40) NOT NULL,
	user_id numeric(38) NOT NULL
) ;

CREATE TABLE org_qprofiles (
	uuid varchar(255) NOT NULL,
	organization_uuid varchar(40) NOT NULL,
	rules_profile_uuid varchar(255) NOT NULL,
	parent_uuid varchar(255),
	last_used numeric(38),
	user_updated_at numeric(38),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE permission_templates (
	id numeric(38) NOT NULL,
	name varchar(100) NOT NULL,
	kee varchar(100) NOT NULL,
	description varchar(4000),
	created_at timestamp,
	updated_at timestamp,
	key_pattern varchar(500),
	organization_uuid varchar(40) NOT NULL
) ;

CREATE TABLE perm_templates_groups (
	id numeric(38) NOT NULL,
	group_id numeric(38),
	template_id numeric(38) NOT NULL,
	permission_reference varchar(64) NOT NULL,
	created_at timestamp,
	updated_at timestamp
) ;

CREATE TABLE perm_templates_users (
	id numeric(38) NOT NULL,
	user_id numeric(38) NOT NULL,
	template_id numeric(38) NOT NULL,
	permission_reference varchar(64) NOT NULL,
	created_at timestamp,
	updated_at timestamp
) ;

CREATE TABLE perm_tpl_characteristics (
	id numeric(38) NOT NULL,
	template_id numeric(38) NOT NULL,
	permission_key varchar(64) NOT NULL,
	with_project_creator smallint NOT NULL DEFAULT 0,
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE plugins (
	uuid varchar(40) NOT NULL,
	kee varchar(200) NOT NULL,
	base_plugin_key varchar(200),
	file_hash varchar(200) NOT NULL,
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE projects (
	id numeric(38) NOT NULL,
	name varchar(2000),
	description varchar(2000),
	enabled smallint NOT NULL DEFAULT 1,
	scope varchar(3),
	qualifier varchar(10),
	kee varchar(400),
	language varchar(20),
	long_name varchar(2000),
	created_at timestamp,
	path varchar(2000),
	deprecated_kee varchar(400),
	uuid varchar(50) NOT NULL,
	project_uuid varchar(50) NOT NULL,
	module_uuid varchar(50),
	module_uuid_path varchar(1500),
	authorization_updated_at numeric(38),
	root_uuid varchar(50) NOT NULL,
	copy_component_uuid varchar(50),
	developer_uuid varchar(50),
	uuid_path varchar(1500) NOT NULL,
	b_changed smallint,
	b_copy_component_uuid varchar(50),
	b_description varchar(2000),
	b_enabled smallint,
	b_language varchar(20),
	b_long_name varchar(500),
	b_module_uuid varchar(50),
	b_module_uuid_path varchar(1500),
	b_name varchar(500),
	b_path varchar(2000),
	b_qualifier varchar(10),
	b_uuid_path varchar(1500),
	organization_uuid varchar(40) NOT NULL,
	tags varchar(500),
	private smallint NOT NULL,
	main_branch_project_uuid varchar(50)
) ;

CREATE TABLE project_branches (
	uuid varchar(50) NOT NULL,
	project_uuid varchar(50) NOT NULL,
	kee varchar(255) NOT NULL,
	branch_type varchar(5),
	merge_branch_uuid varchar(50),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE project_links (
	id numeric(38) NOT NULL,
	link_type varchar(20),
	name varchar(128),
	href varchar(2048) NOT NULL,
	component_uuid varchar(2048)
) ;

CREATE TABLE project_measures (
	id numeric(38) NOT NULL,
	value decimal(38,20),
	metric_id numeric(38) NOT NULL,
	text_value varchar(4000),
	alert_status varchar(5),
	alert_text varchar(4000),
	description varchar(4000),
	person_id numeric(38),
	variation_value_1 decimal(38,20),
	variation_value_2 decimal(38,20),
	variation_value_3 decimal(38,20),
	variation_value_4 decimal(38,20),
	variation_value_5 decimal(38,20),
	measure_data bytea,
	component_uuid varchar(50) NOT NULL,
	analysis_uuid varchar(50) NOT NULL
) ;

CREATE TABLE project_qprofiles (
	id numeric(38) NOT NULL,
	project_uuid varchar(50) NOT NULL,
	profile_key varchar(50) NOT NULL
) ;

CREATE TABLE properties (
	id numeric(38) NOT NULL,
	prop_key varchar(512) NOT NULL,
	resource_id numeric(38),
	user_id numeric(38),
	is_empty smallint NOT NULL,
	text_value varchar(4000),
	clob_value text,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE qprofile_changes (
	kee varchar(40) NOT NULL,
	rules_profile_uuid varchar(255) NOT NULL,
	change_type varchar(20) NOT NULL,
	user_login varchar(255),
	change_data text,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE qprofile_edit_groups (
	uuid varchar(40) NOT NULL,
	group_id numeric(38) NOT NULL,
	qprofile_uuid varchar(255) NOT NULL,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE qprofile_edit_users (
	uuid varchar(40) NOT NULL,
	user_id numeric(38) NOT NULL,
	qprofile_uuid varchar(255) NOT NULL,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE quality_gates (
	id numeric(38) NOT NULL,
	name varchar(100) NOT NULL,
	created_at timestamp,
	updated_at timestamp
) ;

CREATE TABLE quality_gate_conditions (
	id numeric(38) NOT NULL,
	qgate_id numeric(38),
	metric_id numeric(38),
	period numeric(38),
	operator varchar(3),
	value_error varchar(64),
	value_warning varchar(64),
	created_at timestamp,
	updated_at timestamp
) ;

CREATE TABLE rules (
	id numeric(38) NOT NULL,
	name varchar(200),
	plugin_rule_key varchar(200) NOT NULL,
	plugin_config_key varchar(200),
	plugin_name varchar(255) NOT NULL,
	description text,
	priority numeric(38),
	template_id numeric(38),
	status varchar(40),
	language varchar(20),
	def_remediation_function varchar(20),
	def_remediation_gap_mult varchar(20),
	def_remediation_base_effort varchar(20),
	gap_description varchar(4000),
	system_tags varchar(4000),
	is_template smallint NOT NULL DEFAULT 0,
	description_format varchar(20),
	created_at numeric(38),
	updated_at numeric(38),
	rule_type smallint,
	plugin_key varchar(200)
) ;

CREATE TABLE rules_metadata (
	rule_id numeric(38) NOT NULL,
	organization_uuid varchar(40) NOT NULL,
	note_data text,
	note_user_login varchar(255),
	note_created_at numeric(38),
	note_updated_at numeric(38),
	remediation_function varchar(20),
	remediation_gap_mult varchar(20),
	remediation_base_effort varchar(20),
	tags varchar(4000),
	created_at numeric(38) NOT NULL,
	updated_at numeric(38) NOT NULL
) ;

CREATE TABLE rules_parameters (
	id numeric(38) NOT NULL,
	rule_id numeric(38) NOT NULL,
	name varchar(128) NOT NULL,
	description varchar(4000),
	param_type varchar(512) NOT NULL,
	default_value varchar(4000)
) ;

CREATE TABLE rules_profiles (
	id numeric(38) NOT NULL,
	name varchar(100) NOT NULL,
	language varchar(20),
	kee varchar(255) NOT NULL,
	rules_updated_at varchar(100),
	created_at timestamp,
	updated_at timestamp,
	is_built_in smallint NOT NULL
) ;

CREATE TABLE rule_repositories (
	kee varchar(200) NOT NULL,
	language varchar(20) NOT NULL,
	name varchar(4000) NOT NULL,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE schema_migrations (
	version varchar(255) NOT NULL
) ;

CREATE TABLE snapshots (
	id numeric(38) NOT NULL,
	status varchar(4) NOT NULL DEFAULT 'U',
	islast smallint NOT NULL DEFAULT 0,
	version varchar(500),
	purge_status numeric(38),
	period1_mode varchar(100),
	period1_param varchar(100),
	period2_mode varchar(100),
	period2_param varchar(100),
	period3_mode varchar(100),
	period3_param varchar(100),
	period4_mode varchar(100),
	period4_param varchar(100),
	period5_mode varchar(100),
	period5_param varchar(100),
	created_at numeric(38),
	build_date numeric(38),
	period1_date numeric(38),
	period2_date numeric(38),
	period3_date numeric(38),
	period4_date numeric(38),
	period5_date numeric(38),
	component_uuid varchar(50) NOT NULL,
	uuid varchar(50) NOT NULL
) ;

CREATE TABLE users (
	id numeric(38) NOT NULL,
	login varchar(255),
	name varchar(200),
	email varchar(100),
	crypted_password varchar(40),
	salt varchar(40),
	active smallint DEFAULT 1,
	created_at numeric(38),
	updated_at numeric(38),
	scm_accounts varchar(4000),
	external_identity varchar(255),
	external_identity_provider varchar(100),
	user_local smallint,
	is_root smallint NOT NULL,
	onboarded smallint NOT NULL
) ;

CREATE TABLE user_roles (
	id numeric(38) NOT NULL,
	user_id numeric(38),
	resource_id numeric(38),
	role varchar(64) NOT NULL,
	organization_uuid varchar(40) NOT NULL
) ;

CREATE TABLE user_tokens (
	id numeric(38) NOT NULL,
	login varchar(255) NOT NULL,
	name varchar(100) NOT NULL,
	token_hash varchar(255) NOT NULL,
	created_at numeric(38) NOT NULL
) ;

CREATE TABLE webhook_deliveries (
	uuid varchar(40) NOT NULL,
	component_uuid varchar(40) NOT NULL,
	ce_task_uuid varchar(40),
	name varchar(100) NOT NULL,
	url varchar(2000) NOT NULL,
	success smallint NOT NULL,
	http_status numeric(38),
	duration_ms numeric(38),
	payload text NOT NULL,
	error_stacktrace text,
	created_at numeric(38) NOT NULL,
	analysis_uuid varchar(40)
) ;
